# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tack < Formula
  desc "Configuration management and system bootstrapping tool inspired by Ansible"
  homepage "https://github.com/tackhq/tack"
  version "1.0.56"
  license "MIT"

  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tackhq/tack/releases/download/v1.0.56/tack_1.0.56_darwin_amd64.tar.gz"
      sha256 "b08a588df2285323fa65516547e0179ae019a7c3865d461e38baa8c6b655d3ca"

      define_method(:install) do
        bin.install "tack"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tackhq/tack/releases/download/v1.0.56/tack_1.0.56_darwin_arm64.tar.gz"
      sha256 "950116330d11f0c7c847308955b1f03102eada1fc646e6c9d4817f7ba1b39ad7"

      define_method(:install) do
        bin.install "tack"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tackhq/tack/releases/download/v1.0.56/tack_1.0.56_linux_amd64.tar.gz"
      sha256 "a30db2730af4607f6beb5a05a575f23f3aca4422218eba7f45d565447feff0e2"
      define_method(:install) do
        bin.install "tack"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tackhq/tack/releases/download/v1.0.56/tack_1.0.56_linux_arm64.tar.gz"
      sha256 "b8ecc06e067f70fb2cdc2f11ca3c669a6fe9527ba4b5349ca22bd33c5ed61cce"
      define_method(:install) do
        bin.install "tack"
      end
    end
  end

  test do
    system "#{bin}/tack", "--version"
  end
end
